/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ConfidentialTreasuryManager {
  export type RebalanceExecutionStruct = {
    timestamp: BigNumberish;
    executor: AddressLike;
    deviation: BigNumberish;
    instructionHash: BytesLike;
    approved: boolean;
  };

  export type RebalanceExecutionStructOutput = [
    timestamp: bigint,
    executor: string,
    deviation: bigint,
    instructionHash: string,
    approved: boolean
  ] & {
    timestamp: bigint;
    executor: string;
    deviation: bigint;
    instructionHash: string;
    approved: boolean;
  };
}

export interface ConfidentialTreasuryManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "GOVERNANCE_ROLE"
      | "MAX_HISTORY"
      | "MIN_REBALANCE_INTERVAL"
      | "STRATEGY_MANAGER_ROLE"
      | "TREASURY_OPERATOR_ROLE"
      | "activateStrategy"
      | "approveRebalanceInstructions"
      | "approvedInstructions"
      | "deactivateStrategy"
      | "executeRebalance"
      | "getRebalanceExecution"
      | "getRebalanceHistoryCount"
      | "getRecentRebalances"
      | "getRoleAdmin"
      | "getStrategyMetadata"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "isApproved"
      | "rebalanceHistory"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "updateStrategy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Initialized"
      | "RebalanceApproved"
      | "RebalanceExecuted"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "StrategyActivated"
      | "StrategyDeactivated"
      | "StrategyUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNANCE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_HISTORY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_REBALANCE_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STRATEGY_MANAGER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TREASURY_OPERATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activateStrategy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveRebalanceInstructions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approvedInstructions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateStrategy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeRebalance",
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getRebalanceExecution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRebalanceHistoryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentRebalances",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStrategyMetadata",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isApproved",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rebalanceHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStrategy",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNANCE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_HISTORY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_REBALANCE_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STRATEGY_MANAGER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TREASURY_OPERATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activateStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveRebalanceInstructions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approvedInstructions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateStrategy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeRebalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRebalanceExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRebalanceHistoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentRebalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStrategyMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isApproved", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rebalanceHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStrategy",
    data: BytesLike
  ): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalanceApprovedEvent {
  export type InputTuple = [
    instructionHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [instructionHash: string, timestamp: bigint];
  export interface OutputObject {
    instructionHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalanceExecutedEvent {
  export type InputTuple = [
    timestamp: BigNumberish,
    executor: AddressLike,
    deviation: BigNumberish,
    instructionHash: BytesLike
  ];
  export type OutputTuple = [
    timestamp: bigint,
    executor: string,
    deviation: bigint,
    instructionHash: string
  ];
  export interface OutputObject {
    timestamp: bigint;
    executor: string;
    deviation: bigint;
    instructionHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyActivatedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyDeactivatedEvent {
  export type InputTuple = [timestamp: BigNumberish];
  export type OutputTuple = [timestamp: bigint];
  export interface OutputObject {
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StrategyUpdatedEvent {
  export type InputTuple = [timestamp: BigNumberish, updatedBy: AddressLike];
  export type OutputTuple = [timestamp: bigint, updatedBy: string];
  export interface OutputObject {
    timestamp: bigint;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialTreasuryManager extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialTreasuryManager;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialTreasuryManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GOVERNANCE_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_HISTORY: TypedContractMethod<[], [bigint], "view">;

  MIN_REBALANCE_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  STRATEGY_MANAGER_ROLE: TypedContractMethod<[], [string], "view">;

  TREASURY_OPERATOR_ROLE: TypedContractMethod<[], [string], "view">;

  activateStrategy: TypedContractMethod<[], [void], "nonpayable">;

  approveRebalanceInstructions: TypedContractMethod<
    [instructionHash: BytesLike],
    [void],
    "nonpayable"
  >;

  approvedInstructions: TypedContractMethod<
    [arg0: BytesLike],
    [boolean],
    "view"
  >;

  deactivateStrategy: TypedContractMethod<[], [void], "nonpayable">;

  executeRebalance: TypedContractMethod<
    [currentBalances: BigNumberish[], currentPrices: BigNumberish[]],
    [string],
    "nonpayable"
  >;

  getRebalanceExecution: TypedContractMethod<
    [index: BigNumberish],
    [ConfidentialTreasuryManager.RebalanceExecutionStructOutput],
    "view"
  >;

  getRebalanceHistoryCount: TypedContractMethod<[], [bigint], "view">;

  getRecentRebalances: TypedContractMethod<
    [count: BigNumberish],
    [ConfidentialTreasuryManager.RebalanceExecutionStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getStrategyMetadata: TypedContractMethod<
    [],
    [
      [bigint, bigint, string, boolean] & {
        lastExecuted: bigint;
        lastUpdated: bigint;
        updatedBy: string;
        active: boolean;
      }
    ],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  isApproved: TypedContractMethod<
    [instructionHash: BytesLike],
    [boolean],
    "view"
  >;

  rebalanceHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, boolean] & {
        timestamp: bigint;
        executor: string;
        deviation: bigint;
        instructionHash: string;
        approved: boolean;
      }
    ],
    "view"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateStrategy: TypedContractMethod<
    [
      encryptedAllocation: BytesLike,
      encryptedRebalanceThreshold: BytesLike,
      encryptedSlippageTolerance: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GOVERNANCE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_HISTORY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_REBALANCE_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STRATEGY_MANAGER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TREASURY_OPERATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activateStrategy"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveRebalanceInstructions"
  ): TypedContractMethod<[instructionHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approvedInstructions"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deactivateStrategy"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeRebalance"
  ): TypedContractMethod<
    [currentBalances: BigNumberish[], currentPrices: BigNumberish[]],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRebalanceExecution"
  ): TypedContractMethod<
    [index: BigNumberish],
    [ConfidentialTreasuryManager.RebalanceExecutionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRebalanceHistoryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRecentRebalances"
  ): TypedContractMethod<
    [count: BigNumberish],
    [ConfidentialTreasuryManager.RebalanceExecutionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getStrategyMetadata"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, string, boolean] & {
        lastExecuted: bigint;
        lastUpdated: bigint;
        updatedBy: string;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isApproved"
  ): TypedContractMethod<[instructionHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "rebalanceHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, boolean] & {
        timestamp: bigint;
        executor: string;
        deviation: bigint;
        instructionHash: string;
        approved: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateStrategy"
  ): TypedContractMethod<
    [
      encryptedAllocation: BytesLike,
      encryptedRebalanceThreshold: BytesLike,
      encryptedSlippageTolerance: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "RebalanceApproved"
  ): TypedContractEvent<
    RebalanceApprovedEvent.InputTuple,
    RebalanceApprovedEvent.OutputTuple,
    RebalanceApprovedEvent.OutputObject
  >;
  getEvent(
    key: "RebalanceExecuted"
  ): TypedContractEvent<
    RebalanceExecutedEvent.InputTuple,
    RebalanceExecutedEvent.OutputTuple,
    RebalanceExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyActivated"
  ): TypedContractEvent<
    StrategyActivatedEvent.InputTuple,
    StrategyActivatedEvent.OutputTuple,
    StrategyActivatedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyDeactivated"
  ): TypedContractEvent<
    StrategyDeactivatedEvent.InputTuple,
    StrategyDeactivatedEvent.OutputTuple,
    StrategyDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "StrategyUpdated"
  ): TypedContractEvent<
    StrategyUpdatedEvent.InputTuple,
    StrategyUpdatedEvent.OutputTuple,
    StrategyUpdatedEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "RebalanceApproved(bytes32,uint256)": TypedContractEvent<
      RebalanceApprovedEvent.InputTuple,
      RebalanceApprovedEvent.OutputTuple,
      RebalanceApprovedEvent.OutputObject
    >;
    RebalanceApproved: TypedContractEvent<
      RebalanceApprovedEvent.InputTuple,
      RebalanceApprovedEvent.OutputTuple,
      RebalanceApprovedEvent.OutputObject
    >;

    "RebalanceExecuted(uint256,address,uint256,bytes32)": TypedContractEvent<
      RebalanceExecutedEvent.InputTuple,
      RebalanceExecutedEvent.OutputTuple,
      RebalanceExecutedEvent.OutputObject
    >;
    RebalanceExecuted: TypedContractEvent<
      RebalanceExecutedEvent.InputTuple,
      RebalanceExecutedEvent.OutputTuple,
      RebalanceExecutedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "StrategyActivated(uint256)": TypedContractEvent<
      StrategyActivatedEvent.InputTuple,
      StrategyActivatedEvent.OutputTuple,
      StrategyActivatedEvent.OutputObject
    >;
    StrategyActivated: TypedContractEvent<
      StrategyActivatedEvent.InputTuple,
      StrategyActivatedEvent.OutputTuple,
      StrategyActivatedEvent.OutputObject
    >;

    "StrategyDeactivated(uint256)": TypedContractEvent<
      StrategyDeactivatedEvent.InputTuple,
      StrategyDeactivatedEvent.OutputTuple,
      StrategyDeactivatedEvent.OutputObject
    >;
    StrategyDeactivated: TypedContractEvent<
      StrategyDeactivatedEvent.InputTuple,
      StrategyDeactivatedEvent.OutputTuple,
      StrategyDeactivatedEvent.OutputObject
    >;

    "StrategyUpdated(uint256,address)": TypedContractEvent<
      StrategyUpdatedEvent.InputTuple,
      StrategyUpdatedEvent.OutputTuple,
      StrategyUpdatedEvent.OutputObject
    >;
    StrategyUpdated: TypedContractEvent<
      StrategyUpdatedEvent.InputTuple,
      StrategyUpdatedEvent.OutputTuple,
      StrategyUpdatedEvent.OutputObject
    >;
  };
}
