/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ConfidentialRiskThresholds {
  export type ThresholdEvaluationStruct = {
    timestamp: BigNumberish;
    evaluator: AddressLike;
    action: string;
    evaluationHash: BytesLike;
  };

  export type ThresholdEvaluationStructOutput = [
    timestamp: bigint,
    evaluator: string,
    action: string,
    evaluationHash: string
  ] & {
    timestamp: bigint;
    evaluator: string;
    action: string;
    evaluationHash: string;
  };
}

export interface ConfidentialRiskThresholdsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AUDITOR_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "EVALUATOR_ROLE"
      | "GUARDIAN_ROLE"
      | "MAX_HISTORY"
      | "evaluateRiskScore"
      | "evaluationHistory"
      | "getEvaluation"
      | "getEvaluationHistoryCount"
      | "getRecentEvaluations"
      | "getRoleAdmin"
      | "getThresholdMetadata"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "updateThresholds"
      | "verifyThresholdForAuditor"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AuditorAccessGranted"
      | "Initialized"
      | "RiskEvaluated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "ThresholdsUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AUDITOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EVALUATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GUARDIAN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_HISTORY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "evaluateRiskScore",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "evaluationHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvaluation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvaluationHistoryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentEvaluations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getThresholdMetadata",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateThresholds",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyThresholdForAuditor",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "AUDITOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EVALUATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GUARDIAN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_HISTORY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evaluateRiskScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "evaluationHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvaluation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvaluationHistoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentEvaluations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getThresholdMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyThresholdForAuditor",
    data: BytesLike
  ): Result;
}

export namespace AuditorAccessGrantedEvent {
  export type InputTuple = [auditor: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [auditor: string, timestamp: bigint];
  export interface OutputObject {
    auditor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskEvaluatedEvent {
  export type InputTuple = [
    timestamp: BigNumberish,
    evaluator: AddressLike,
    action: string,
    evaluationHash: BytesLike
  ];
  export type OutputTuple = [
    timestamp: bigint,
    evaluator: string,
    action: string,
    evaluationHash: string
  ];
  export interface OutputObject {
    timestamp: bigint;
    evaluator: string;
    action: string;
    evaluationHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdsUpdatedEvent {
  export type InputTuple = [timestamp: BigNumberish, updatedBy: AddressLike];
  export type OutputTuple = [timestamp: bigint, updatedBy: string];
  export interface OutputObject {
    timestamp: bigint;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConfidentialRiskThresholds extends BaseContract {
  connect(runner?: ContractRunner | null): ConfidentialRiskThresholds;
  waitForDeployment(): Promise<this>;

  interface: ConfidentialRiskThresholdsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AUDITOR_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EVALUATOR_ROLE: TypedContractMethod<[], [string], "view">;

  GUARDIAN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_HISTORY: TypedContractMethod<[], [bigint], "view">;

  evaluateRiskScore: TypedContractMethod<
    [riskScore: BigNumberish],
    [string],
    "nonpayable"
  >;

  evaluationHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string] & {
        timestamp: bigint;
        evaluator: string;
        action: string;
        evaluationHash: string;
      }
    ],
    "view"
  >;

  getEvaluation: TypedContractMethod<
    [index: BigNumberish],
    [ConfidentialRiskThresholds.ThresholdEvaluationStructOutput],
    "view"
  >;

  getEvaluationHistoryCount: TypedContractMethod<[], [bigint], "view">;

  getRecentEvaluations: TypedContractMethod<
    [count: BigNumberish],
    [ConfidentialRiskThresholds.ThresholdEvaluationStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getThresholdMetadata: TypedContractMethod<
    [],
    [[bigint, string] & { lastUpdated: bigint; updatedBy: string }],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateThresholds: TypedContractMethod<
    [
      encryptedModerate: BytesLike,
      encryptedElevated: BytesLike,
      encryptedCritical: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  verifyThresholdForAuditor: TypedContractMethod<
    [auditorPublicKey: BytesLike, thresholdType: string],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AUDITOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EVALUATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GUARDIAN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_HISTORY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "evaluateRiskScore"
  ): TypedContractMethod<[riskScore: BigNumberish], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "evaluationHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string] & {
        timestamp: bigint;
        evaluator: string;
        action: string;
        evaluationHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvaluation"
  ): TypedContractMethod<
    [index: BigNumberish],
    [ConfidentialRiskThresholds.ThresholdEvaluationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvaluationHistoryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRecentEvaluations"
  ): TypedContractMethod<
    [count: BigNumberish],
    [ConfidentialRiskThresholds.ThresholdEvaluationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getThresholdMetadata"
  ): TypedContractMethod<
    [],
    [[bigint, string] & { lastUpdated: bigint; updatedBy: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateThresholds"
  ): TypedContractMethod<
    [
      encryptedModerate: BytesLike,
      encryptedElevated: BytesLike,
      encryptedCritical: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyThresholdForAuditor"
  ): TypedContractMethod<
    [auditorPublicKey: BytesLike, thresholdType: string],
    [string],
    "view"
  >;

  getEvent(
    key: "AuditorAccessGranted"
  ): TypedContractEvent<
    AuditorAccessGrantedEvent.InputTuple,
    AuditorAccessGrantedEvent.OutputTuple,
    AuditorAccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "RiskEvaluated"
  ): TypedContractEvent<
    RiskEvaluatedEvent.InputTuple,
    RiskEvaluatedEvent.OutputTuple,
    RiskEvaluatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdsUpdated"
  ): TypedContractEvent<
    ThresholdsUpdatedEvent.InputTuple,
    ThresholdsUpdatedEvent.OutputTuple,
    ThresholdsUpdatedEvent.OutputObject
  >;

  filters: {
    "AuditorAccessGranted(address,uint256)": TypedContractEvent<
      AuditorAccessGrantedEvent.InputTuple,
      AuditorAccessGrantedEvent.OutputTuple,
      AuditorAccessGrantedEvent.OutputObject
    >;
    AuditorAccessGranted: TypedContractEvent<
      AuditorAccessGrantedEvent.InputTuple,
      AuditorAccessGrantedEvent.OutputTuple,
      AuditorAccessGrantedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "RiskEvaluated(uint256,address,string,bytes32)": TypedContractEvent<
      RiskEvaluatedEvent.InputTuple,
      RiskEvaluatedEvent.OutputTuple,
      RiskEvaluatedEvent.OutputObject
    >;
    RiskEvaluated: TypedContractEvent<
      RiskEvaluatedEvent.InputTuple,
      RiskEvaluatedEvent.OutputTuple,
      RiskEvaluatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "ThresholdsUpdated(uint256,address)": TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;
    ThresholdsUpdated: TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;
  };
}
