/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governanceModuleSol from "./GovernanceModule.sol";
export type { governanceModuleSol };
import type * as predictionMarketSol from "./PredictionMarket.sol";
export type { predictionMarketSol };
import type * as riskGuardianSol from "./RiskGuardian.sol";
export type { riskGuardianSol };
import type * as confidential from "./confidential";
export type { confidential };
import type * as mocks from "./mocks";
export type { mocks };
export type { TestImport } from "./TestImport";
export type { TestPrediction } from "./TestPrediction";
export type { TokenizedVault } from "./TokenizedVault";
