/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernanceModule__factory } from "./GovernanceModule__factory";
export { IWorldID__factory } from "./IWorldID__factory";
