/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface GovernanceModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "CRE_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "EMERGENCY_RISK_THRESHOLD"
      | "MAX_EMERGENCY_PERIOD"
      | "MAX_QUORUM"
      | "MAX_VOTING_PERIOD"
      | "MIN_EMERGENCY_PERIOD"
      | "MIN_QUORUM"
      | "MIN_VOTING_PERIOD"
      | "ORACLE_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "cancelProposal"
      | "createEmergencyProposal"
      | "createProposal"
      | "emergencyVotingPeriod"
      | "executeProposal"
      | "externalNullifierHash"
      | "getProposal"
      | "getRoleAdmin"
      | "getVote"
      | "getVoters"
      | "grantRole"
      | "groupId"
      | "guardianMultiSig"
      | "guardianOverride"
      | "guardianOverrides"
      | "hasRole"
      | "hasVoted"
      | "initialize"
      | "isNullifierUsed"
      | "proposalCount"
      | "proposals"
      | "proxiableUUID"
      | "quorumPercentage"
      | "removeTarget"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "totalVerifiedHumans"
      | "updateEmergencyVotingPeriod"
      | "updateGuardianMultiSig"
      | "updateQuorumPercentage"
      | "updateTotalVerifiedHumans"
      | "updateVotingPeriod"
      | "upgradeToAndCall"
      | "vote"
      | "votingPeriod"
      | "whitelistTarget"
      | "whitelistedTargets"
      | "worldId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EmergencyProposalCreated"
      | "GuardianMultiSigUpdated"
      | "GuardianOverride"
      | "Initialized"
      | "ProposalCreated"
      | "ProposalDefeated"
      | "ProposalExecuted"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TargetRemoved"
      | "TargetWhitelisted"
      | "Upgraded"
      | "VerifiedHumansUpdated"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "CRE_ROLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EMERGENCY_RISK_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_EMERGENCY_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_QUORUM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_VOTING_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_EMERGENCY_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_QUORUM",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_VOTING_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORACLE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEmergencyProposal",
    values: [string, string, AddressLike, BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [
      string,
      string,
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BigNumberish[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyVotingPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "externalNullifierHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVote",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "groupId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "guardianMultiSig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "guardianOverride",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "guardianOverrides",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isNullifierUsed",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quorumPercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeTarget",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalVerifiedHumans",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateEmergencyVotingPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGuardianMultiSig",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateQuorumPercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTotalVerifiedHumans",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateVotingPeriod",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, boolean, BigNumberish, BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "votingPeriod",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistTarget",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistedTargets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "worldId", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "CRE_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EMERGENCY_RISK_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_EMERGENCY_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_QUORUM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MAX_VOTING_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_EMERGENCY_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_QUORUM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_VOTING_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORACLE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEmergencyProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyVotingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "externalNullifierHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVoters", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "groupId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "guardianMultiSig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guardianOverride",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "guardianOverrides",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isNullifierUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quorumPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVerifiedHumans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateEmergencyVotingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGuardianMultiSig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateQuorumPercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTotalVerifiedHumans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateVotingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingPeriod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistedTargets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "worldId", data: BytesLike): Result;
}

export namespace EmergencyProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    riskScore: BigNumberish,
    aiReasoning: string,
    votingEndTime: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    riskScore: bigint,
    aiReasoning: string,
    votingEndTime: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    riskScore: bigint;
    aiReasoning: string;
    votingEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuardianMultiSigUpdatedEvent {
  export type InputTuple = [oldGuardian: AddressLike, newGuardian: AddressLike];
  export type OutputTuple = [oldGuardian: string, newGuardian: string];
  export interface OutputObject {
    oldGuardian: string;
    newGuardian: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GuardianOverrideEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    guardian: AddressLike,
    justification: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    guardian: string,
    justification: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    guardian: string;
    justification: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    proposer: AddressLike,
    title: string,
    votingEndTime: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    proposer: string,
    title: string,
    votingEndTime: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    proposer: string;
    title: string;
    votingEndTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalDefeatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    votesFor: BigNumberish,
    votesAgainst: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    votesFor: bigint,
    votesAgainst: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    votesFor: bigint;
    votesAgainst: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [proposalId: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [proposalId: bigint, timestamp: bigint];
  export interface OutputObject {
    proposalId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetRemovedEvent {
  export type InputTuple = [target: AddressLike];
  export type OutputTuple = [target: string];
  export interface OutputObject {
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TargetWhitelistedEvent {
  export type InputTuple = [target: AddressLike];
  export type OutputTuple = [target: string];
  export interface OutputObject {
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifiedHumansUpdatedEvent {
  export type InputTuple = [oldTotal: BigNumberish, newTotal: BigNumberish];
  export type OutputTuple = [oldTotal: bigint, newTotal: bigint];
  export interface OutputObject {
    oldTotal: bigint;
    newTotal: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    voter: AddressLike,
    support: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    voter: string,
    support: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    voter: string;
    support: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GovernanceModule extends BaseContract {
  connect(runner?: ContractRunner | null): GovernanceModule;
  waitForDeployment(): Promise<this>;

  interface: GovernanceModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  CRE_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  EMERGENCY_RISK_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  MAX_EMERGENCY_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MAX_QUORUM: TypedContractMethod<[], [bigint], "view">;

  MAX_VOTING_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MIN_EMERGENCY_PERIOD: TypedContractMethod<[], [bigint], "view">;

  MIN_QUORUM: TypedContractMethod<[], [bigint], "view">;

  MIN_VOTING_PERIOD: TypedContractMethod<[], [bigint], "view">;

  ORACLE_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  cancelProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createEmergencyProposal: TypedContractMethod<
    [
      title: string,
      description: string,
      targetContract: AddressLike,
      callData: BytesLike,
      riskScore: BigNumberish,
      aiReasoning: string
    ],
    [bigint],
    "nonpayable"
  >;

  createProposal: TypedContractMethod<
    [
      title: string,
      description: string,
      targetContract: AddressLike,
      callData: BytesLike,
      merkleRoot: BigNumberish,
      nullifierHash: BigNumberish,
      proof: BigNumberish[]
    ],
    [bigint],
    "nonpayable"
  >;

  emergencyVotingPeriod: TypedContractMethod<[], [bigint], "view">;

  executeProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  externalNullifierHash: TypedContractMethod<[], [bigint], "view">;

  getProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        proposer: string;
        title: string;
        description: string;
        targetContract: string;
        votingEndTime: bigint;
        status: bigint;
        votesFor: bigint;
        votesAgainst: bigint;
        isEmergency: boolean;
      }
    ],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getVote: TypedContractMethod<
    [proposalId: BigNumberish, voter: AddressLike],
    [
      [boolean, bigint, bigint] & {
        support: boolean;
        nullifierHash: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getVoters: TypedContractMethod<
    [proposalId: BigNumberish],
    [string[]],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  groupId: TypedContractMethod<[], [bigint], "view">;

  guardianMultiSig: TypedContractMethod<[], [string], "view">;

  guardianOverride: TypedContractMethod<
    [proposalId: BigNumberish, justification: string],
    [void],
    "nonpayable"
  >;

  guardianOverrides: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [proposalId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _worldId: AddressLike,
      _externalNullifierHash: BigNumberish,
      _groupId: BigNumberish,
      _quorumPercentage: BigNumberish,
      _votingPeriod: BigNumberish,
      _emergencyVotingPeriod: BigNumberish,
      _guardianMultiSig: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isNullifierUsed: TypedContractMethod<
    [proposalId: BigNumberish, nullifierHash: BigNumberish],
    [boolean],
    "view"
  >;

  proposalCount: TypedContractMethod<[], [bigint], "view">;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        string
      ] & {
        proposalId: bigint;
        proposer: string;
        title: string;
        description: string;
        targetContract: string;
        callData: string;
        creationTime: bigint;
        votingEndTime: bigint;
        status: bigint;
        votesFor: bigint;
        votesAgainst: bigint;
        isEmergency: boolean;
        riskScore: bigint;
        aiReasoning: string;
      }
    ],
    "view"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  quorumPercentage: TypedContractMethod<[], [bigint], "view">;

  removeTarget: TypedContractMethod<
    [target: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalVerifiedHumans: TypedContractMethod<[], [bigint], "view">;

  updateEmergencyVotingPeriod: TypedContractMethod<
    [newPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateGuardianMultiSig: TypedContractMethod<
    [newGuardian: AddressLike],
    [void],
    "nonpayable"
  >;

  updateQuorumPercentage: TypedContractMethod<
    [newQuorum: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateTotalVerifiedHumans: TypedContractMethod<
    [newTotal: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateVotingPeriod: TypedContractMethod<
    [newPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  vote: TypedContractMethod<
    [
      proposalId: BigNumberish,
      support: boolean,
      merkleRoot: BigNumberish,
      nullifierHash: BigNumberish,
      proof: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  votingPeriod: TypedContractMethod<[], [bigint], "view">;

  whitelistTarget: TypedContractMethod<
    [target: AddressLike],
    [void],
    "nonpayable"
  >;

  whitelistedTargets: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  worldId: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "CRE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "EMERGENCY_RISK_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_EMERGENCY_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_QUORUM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_VOTING_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_EMERGENCY_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_QUORUM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_VOTING_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ORACLE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelProposal"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createEmergencyProposal"
  ): TypedContractMethod<
    [
      title: string,
      description: string,
      targetContract: AddressLike,
      callData: BytesLike,
      riskScore: BigNumberish,
      aiReasoning: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [
      title: string,
      description: string,
      targetContract: AddressLike,
      callData: BytesLike,
      merkleRoot: BigNumberish,
      nullifierHash: BigNumberish,
      proof: BigNumberish[]
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyVotingPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeProposal"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "externalNullifierHash"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        proposer: string;
        title: string;
        description: string;
        targetContract: string;
        votingEndTime: bigint;
        status: bigint;
        votesFor: bigint;
        votesAgainst: bigint;
        isEmergency: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getVote"
  ): TypedContractMethod<
    [proposalId: BigNumberish, voter: AddressLike],
    [
      [boolean, bigint, bigint] & {
        support: boolean;
        nullifierHash: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVoters"
  ): TypedContractMethod<[proposalId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "groupId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "guardianMultiSig"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "guardianOverride"
  ): TypedContractMethod<
    [proposalId: BigNumberish, justification: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "guardianOverrides"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [proposalId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _worldId: AddressLike,
      _externalNullifierHash: BigNumberish,
      _groupId: BigNumberish,
      _quorumPercentage: BigNumberish,
      _votingPeriod: BigNumberish,
      _emergencyVotingPeriod: BigNumberish,
      _guardianMultiSig: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isNullifierUsed"
  ): TypedContractMethod<
    [proposalId: BigNumberish, nullifierHash: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        string
      ] & {
        proposalId: bigint;
        proposer: string;
        title: string;
        description: string;
        targetContract: string;
        callData: string;
        creationTime: bigint;
        votingEndTime: bigint;
        status: bigint;
        votesFor: bigint;
        votesAgainst: bigint;
        isEmergency: boolean;
        riskScore: bigint;
        aiReasoning: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quorumPercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeTarget"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalVerifiedHumans"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updateEmergencyVotingPeriod"
  ): TypedContractMethod<[newPeriod: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateGuardianMultiSig"
  ): TypedContractMethod<[newGuardian: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateQuorumPercentage"
  ): TypedContractMethod<[newQuorum: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTotalVerifiedHumans"
  ): TypedContractMethod<[newTotal: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateVotingPeriod"
  ): TypedContractMethod<[newPeriod: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [
      proposalId: BigNumberish,
      support: boolean,
      merkleRoot: BigNumberish,
      nullifierHash: BigNumberish,
      proof: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "votingPeriod"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "whitelistTarget"
  ): TypedContractMethod<[target: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "whitelistedTargets"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "worldId"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "EmergencyProposalCreated"
  ): TypedContractEvent<
    EmergencyProposalCreatedEvent.InputTuple,
    EmergencyProposalCreatedEvent.OutputTuple,
    EmergencyProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "GuardianMultiSigUpdated"
  ): TypedContractEvent<
    GuardianMultiSigUpdatedEvent.InputTuple,
    GuardianMultiSigUpdatedEvent.OutputTuple,
    GuardianMultiSigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "GuardianOverride"
  ): TypedContractEvent<
    GuardianOverrideEvent.InputTuple,
    GuardianOverrideEvent.OutputTuple,
    GuardianOverrideEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalDefeated"
  ): TypedContractEvent<
    ProposalDefeatedEvent.InputTuple,
    ProposalDefeatedEvent.OutputTuple,
    ProposalDefeatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TargetRemoved"
  ): TypedContractEvent<
    TargetRemovedEvent.InputTuple,
    TargetRemovedEvent.OutputTuple,
    TargetRemovedEvent.OutputObject
  >;
  getEvent(
    key: "TargetWhitelisted"
  ): TypedContractEvent<
    TargetWhitelistedEvent.InputTuple,
    TargetWhitelistedEvent.OutputTuple,
    TargetWhitelistedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "VerifiedHumansUpdated"
  ): TypedContractEvent<
    VerifiedHumansUpdatedEvent.InputTuple,
    VerifiedHumansUpdatedEvent.OutputTuple,
    VerifiedHumansUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "EmergencyProposalCreated(uint256,uint256,string,uint256)": TypedContractEvent<
      EmergencyProposalCreatedEvent.InputTuple,
      EmergencyProposalCreatedEvent.OutputTuple,
      EmergencyProposalCreatedEvent.OutputObject
    >;
    EmergencyProposalCreated: TypedContractEvent<
      EmergencyProposalCreatedEvent.InputTuple,
      EmergencyProposalCreatedEvent.OutputTuple,
      EmergencyProposalCreatedEvent.OutputObject
    >;

    "GuardianMultiSigUpdated(address,address)": TypedContractEvent<
      GuardianMultiSigUpdatedEvent.InputTuple,
      GuardianMultiSigUpdatedEvent.OutputTuple,
      GuardianMultiSigUpdatedEvent.OutputObject
    >;
    GuardianMultiSigUpdated: TypedContractEvent<
      GuardianMultiSigUpdatedEvent.InputTuple,
      GuardianMultiSigUpdatedEvent.OutputTuple,
      GuardianMultiSigUpdatedEvent.OutputObject
    >;

    "GuardianOverride(uint256,address,string,uint256)": TypedContractEvent<
      GuardianOverrideEvent.InputTuple,
      GuardianOverrideEvent.OutputTuple,
      GuardianOverrideEvent.OutputObject
    >;
    GuardianOverride: TypedContractEvent<
      GuardianOverrideEvent.InputTuple,
      GuardianOverrideEvent.OutputTuple,
      GuardianOverrideEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "ProposalCreated(uint256,address,string,uint256)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalDefeated(uint256,uint256,uint256)": TypedContractEvent<
      ProposalDefeatedEvent.InputTuple,
      ProposalDefeatedEvent.OutputTuple,
      ProposalDefeatedEvent.OutputObject
    >;
    ProposalDefeated: TypedContractEvent<
      ProposalDefeatedEvent.InputTuple,
      ProposalDefeatedEvent.OutputTuple,
      ProposalDefeatedEvent.OutputObject
    >;

    "ProposalExecuted(uint256,uint256)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TargetRemoved(address)": TypedContractEvent<
      TargetRemovedEvent.InputTuple,
      TargetRemovedEvent.OutputTuple,
      TargetRemovedEvent.OutputObject
    >;
    TargetRemoved: TypedContractEvent<
      TargetRemovedEvent.InputTuple,
      TargetRemovedEvent.OutputTuple,
      TargetRemovedEvent.OutputObject
    >;

    "TargetWhitelisted(address)": TypedContractEvent<
      TargetWhitelistedEvent.InputTuple,
      TargetWhitelistedEvent.OutputTuple,
      TargetWhitelistedEvent.OutputObject
    >;
    TargetWhitelisted: TypedContractEvent<
      TargetWhitelistedEvent.InputTuple,
      TargetWhitelistedEvent.OutputTuple,
      TargetWhitelistedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "VerifiedHumansUpdated(uint256,uint256)": TypedContractEvent<
      VerifiedHumansUpdatedEvent.InputTuple,
      VerifiedHumansUpdatedEvent.OutputTuple,
      VerifiedHumansUpdatedEvent.OutputObject
    >;
    VerifiedHumansUpdated: TypedContractEvent<
      VerifiedHumansUpdatedEvent.InputTuple,
      VerifiedHumansUpdatedEvent.OutputTuple,
      VerifiedHumansUpdatedEvent.OutputObject
    >;

    "VoteCast(uint256,address,bool,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
