/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGovernanceModule,
  IGovernanceModuleInterface,
} from "../../../contracts/RiskGuardian.sol/IGovernanceModule";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "title",
        type: "string",
      },
      {
        internalType: "string",
        name: "description",
        type: "string",
      },
      {
        internalType: "address",
        name: "targetContract",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "callData",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "riskScore",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "aiReasoning",
        type: "string",
      },
    ],
    name: "createEmergencyProposal",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IGovernanceModule__factory {
  static readonly abi = _abi;
  static createInterface(): IGovernanceModuleInterface {
    return new Interface(_abi) as IGovernanceModuleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGovernanceModule {
    return new Contract(address, _abi, runner) as unknown as IGovernanceModule;
  }
}
