/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITokenizedVault,
  ITokenizedVaultInterface,
} from "../../../contracts/RiskGuardian.sol/ITokenizedVault";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "newRatio",
        type: "uint256",
      },
    ],
    name: "adjustMinimumReserveRatio",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "calculateReserveRatio",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "emergencyPause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITokenizedVault__factory {
  static readonly abi = _abi;
  static createInterface(): ITokenizedVaultInterface {
    return new Interface(_abi) as ITokenizedVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITokenizedVault {
    return new Contract(address, _abi, runner) as unknown as ITokenizedVault;
  }
}
