/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IWorldID__factory } from "./IWorldID__factory";
export { PredictionMarket__factory } from "./PredictionMarket__factory";
