/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IGovernanceModuleInterface extends Interface {
  getFunction(nameOrSignature: "createEmergencyProposal"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createEmergencyProposal",
    values: [string, string, AddressLike, BytesLike, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "createEmergencyProposal",
    data: BytesLike
  ): Result;
}

export interface IGovernanceModule extends BaseContract {
  connect(runner?: ContractRunner | null): IGovernanceModule;
  waitForDeployment(): Promise<this>;

  interface: IGovernanceModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createEmergencyProposal: TypedContractMethod<
    [
      title: string,
      description: string,
      targetContract: AddressLike,
      callData: BytesLike,
      riskScore: BigNumberish,
      aiReasoning: string
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createEmergencyProposal"
  ): TypedContractMethod<
    [
      title: string,
      description: string,
      targetContract: AddressLike,
      callData: BytesLike,
      riskScore: BigNumberish,
      aiReasoning: string
    ],
    [bigint],
    "nonpayable"
  >;

  filters: {};
}
