/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace RiskGuardian {
  export type RiskSignalStruct = {
    riskScore: BigNumberish;
    recommendedAction: string;
    confidence: BigNumberish;
    reasoning: string;
    timestamp: BigNumberish;
    triggeredBy: AddressLike;
  };

  export type RiskSignalStructOutput = [
    riskScore: bigint,
    recommendedAction: string,
    confidence: bigint,
    reasoning: string,
    timestamp: bigint,
    triggeredBy: string
  ] & {
    riskScore: bigint;
    recommendedAction: string;
    confidence: bigint;
    reasoning: string;
    timestamp: bigint;
    triggeredBy: string;
  };
}

export interface RiskGuardianInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "GUARDIAN_ROLE"
      | "UPGRADE_INTERFACE_VERSION"
      | "addAuthorizedCREWorkflow"
      | "authorizedCREWorkflows"
      | "creWorkflowList"
      | "criticalRiskThreshold"
      | "elevatedRiskThreshold"
      | "executeRiskResponse"
      | "getAuthorizedWorkflows"
      | "getRiskSignalHistory"
      | "getRoleAdmin"
      | "governanceContract"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "isAuthorizedWorkflow"
      | "lastSafeguardExecution"
      | "moderateRiskThreshold"
      | "proxiableUUID"
      | "removeAuthorizedCREWorkflow"
      | "renounceRole"
      | "revokeRole"
      | "riskSignalHistory"
      | "safeguardCooldown"
      | "setGovernanceContract"
      | "supportsInterface"
      | "updateSafeguardCooldown"
      | "updateThresholds"
      | "upgradeToAndCall"
      | "vaultContract"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CREWorkflowAuthorized"
      | "CREWorkflowRevoked"
      | "CriticalSafeguardActivated"
      | "ElevatedSafeguardActivated"
      | "Initialized"
      | "RiskResponseExecuted"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "ThresholdsUpdated"
      | "UnauthorizedAccessAttempt"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GUARDIAN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addAuthorizedCREWorkflow",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedCREWorkflows",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "creWorkflowList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "criticalRiskThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "elevatedRiskThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeRiskResponse",
    values: [BigNumberish, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuthorizedWorkflows",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRiskSignalHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "governanceContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedWorkflow",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastSafeguardExecution",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "moderateRiskThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeAuthorizedCREWorkflow",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "riskSignalHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "safeguardCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGovernanceContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSafeguardCooldown",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateThresholds",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultContract",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GUARDIAN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAuthorizedCREWorkflow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedCREWorkflows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creWorkflowList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "criticalRiskThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "elevatedRiskThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeRiskResponse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuthorizedWorkflows",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRiskSignalHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedWorkflow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastSafeguardExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moderateRiskThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAuthorizedCREWorkflow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "riskSignalHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "safeguardCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernanceContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSafeguardCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultContract",
    data: BytesLike
  ): Result;
}

export namespace CREWorkflowAuthorizedEvent {
  export type InputTuple = [workflow: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [workflow: string, timestamp: bigint];
  export interface OutputObject {
    workflow: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CREWorkflowRevokedEvent {
  export type InputTuple = [workflow: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [workflow: string, timestamp: bigint];
  export interface OutputObject {
    workflow: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CriticalSafeguardActivatedEvent {
  export type InputTuple = [
    riskScore: BigNumberish,
    reasoning: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    riskScore: bigint,
    reasoning: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    riskScore: bigint;
    reasoning: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ElevatedSafeguardActivatedEvent {
  export type InputTuple = [
    oldRatio: BigNumberish,
    newRatio: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    oldRatio: bigint,
    newRatio: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    oldRatio: bigint;
    newRatio: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RiskResponseExecutedEvent {
  export type InputTuple = [
    riskScore: BigNumberish,
    action: string,
    confidence: BigNumberish,
    triggeredBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    riskScore: bigint,
    action: string,
    confidence: bigint,
    triggeredBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    riskScore: bigint;
    action: string;
    confidence: bigint;
    triggeredBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdsUpdatedEvent {
  export type InputTuple = [
    moderate: BigNumberish,
    elevated: BigNumberish,
    critical: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    moderate: bigint,
    elevated: bigint,
    critical: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    moderate: bigint;
    elevated: bigint;
    critical: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnauthorizedAccessAttemptEvent {
  export type InputTuple = [attacker: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [attacker: string, timestamp: bigint];
  export interface OutputObject {
    attacker: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RiskGuardian extends BaseContract {
  connect(runner?: ContractRunner | null): RiskGuardian;
  waitForDeployment(): Promise<this>;

  interface: RiskGuardianInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GUARDIAN_ROLE: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  addAuthorizedCREWorkflow: TypedContractMethod<
    [workflowAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedCREWorkflows: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  creWorkflowList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  criticalRiskThreshold: TypedContractMethod<[], [bigint], "view">;

  elevatedRiskThreshold: TypedContractMethod<[], [bigint], "view">;

  executeRiskResponse: TypedContractMethod<
    [
      riskScore: BigNumberish,
      recommendedAction: string,
      confidence: BigNumberish,
      reasoning: string
    ],
    [void],
    "nonpayable"
  >;

  getAuthorizedWorkflows: TypedContractMethod<[], [string[]], "view">;

  getRiskSignalHistory: TypedContractMethod<
    [count: BigNumberish],
    [RiskGuardian.RiskSignalStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  governanceContract: TypedContractMethod<[], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [_vaultContract: AddressLike, _admin: AddressLike],
    [void],
    "nonpayable"
  >;

  isAuthorizedWorkflow: TypedContractMethod<
    [workflow: AddressLike],
    [boolean],
    "view"
  >;

  lastSafeguardExecution: TypedContractMethod<[], [bigint], "view">;

  moderateRiskThreshold: TypedContractMethod<[], [bigint], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  removeAuthorizedCREWorkflow: TypedContractMethod<
    [workflowAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  riskSignalHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, bigint, string] & {
        riskScore: bigint;
        recommendedAction: string;
        confidence: bigint;
        reasoning: string;
        timestamp: bigint;
        triggeredBy: string;
      }
    ],
    "view"
  >;

  safeguardCooldown: TypedContractMethod<[], [bigint], "view">;

  setGovernanceContract: TypedContractMethod<
    [_governanceContract: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  updateSafeguardCooldown: TypedContractMethod<
    [newCooldown: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateThresholds: TypedContractMethod<
    [moderate: BigNumberish, elevated: BigNumberish, critical: BigNumberish],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  vaultContract: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GUARDIAN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addAuthorizedCREWorkflow"
  ): TypedContractMethod<[workflowAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedCREWorkflows"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "creWorkflowList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "criticalRiskThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "elevatedRiskThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeRiskResponse"
  ): TypedContractMethod<
    [
      riskScore: BigNumberish,
      recommendedAction: string,
      confidence: BigNumberish,
      reasoning: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAuthorizedWorkflows"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRiskSignalHistory"
  ): TypedContractMethod<
    [count: BigNumberish],
    [RiskGuardian.RiskSignalStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "governanceContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [_vaultContract: AddressLike, _admin: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isAuthorizedWorkflow"
  ): TypedContractMethod<[workflow: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastSafeguardExecution"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "moderateRiskThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeAuthorizedCREWorkflow"
  ): TypedContractMethod<[workflowAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "riskSignalHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, bigint, string] & {
        riskScore: bigint;
        recommendedAction: string;
        confidence: bigint;
        reasoning: string;
        timestamp: bigint;
        triggeredBy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "safeguardCooldown"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setGovernanceContract"
  ): TypedContractMethod<
    [_governanceContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "updateSafeguardCooldown"
  ): TypedContractMethod<[newCooldown: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateThresholds"
  ): TypedContractMethod<
    [moderate: BigNumberish, elevated: BigNumberish, critical: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "vaultContract"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CREWorkflowAuthorized"
  ): TypedContractEvent<
    CREWorkflowAuthorizedEvent.InputTuple,
    CREWorkflowAuthorizedEvent.OutputTuple,
    CREWorkflowAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "CREWorkflowRevoked"
  ): TypedContractEvent<
    CREWorkflowRevokedEvent.InputTuple,
    CREWorkflowRevokedEvent.OutputTuple,
    CREWorkflowRevokedEvent.OutputObject
  >;
  getEvent(
    key: "CriticalSafeguardActivated"
  ): TypedContractEvent<
    CriticalSafeguardActivatedEvent.InputTuple,
    CriticalSafeguardActivatedEvent.OutputTuple,
    CriticalSafeguardActivatedEvent.OutputObject
  >;
  getEvent(
    key: "ElevatedSafeguardActivated"
  ): TypedContractEvent<
    ElevatedSafeguardActivatedEvent.InputTuple,
    ElevatedSafeguardActivatedEvent.OutputTuple,
    ElevatedSafeguardActivatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "RiskResponseExecuted"
  ): TypedContractEvent<
    RiskResponseExecutedEvent.InputTuple,
    RiskResponseExecutedEvent.OutputTuple,
    RiskResponseExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdsUpdated"
  ): TypedContractEvent<
    ThresholdsUpdatedEvent.InputTuple,
    ThresholdsUpdatedEvent.OutputTuple,
    ThresholdsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UnauthorizedAccessAttempt"
  ): TypedContractEvent<
    UnauthorizedAccessAttemptEvent.InputTuple,
    UnauthorizedAccessAttemptEvent.OutputTuple,
    UnauthorizedAccessAttemptEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "CREWorkflowAuthorized(address,uint256)": TypedContractEvent<
      CREWorkflowAuthorizedEvent.InputTuple,
      CREWorkflowAuthorizedEvent.OutputTuple,
      CREWorkflowAuthorizedEvent.OutputObject
    >;
    CREWorkflowAuthorized: TypedContractEvent<
      CREWorkflowAuthorizedEvent.InputTuple,
      CREWorkflowAuthorizedEvent.OutputTuple,
      CREWorkflowAuthorizedEvent.OutputObject
    >;

    "CREWorkflowRevoked(address,uint256)": TypedContractEvent<
      CREWorkflowRevokedEvent.InputTuple,
      CREWorkflowRevokedEvent.OutputTuple,
      CREWorkflowRevokedEvent.OutputObject
    >;
    CREWorkflowRevoked: TypedContractEvent<
      CREWorkflowRevokedEvent.InputTuple,
      CREWorkflowRevokedEvent.OutputTuple,
      CREWorkflowRevokedEvent.OutputObject
    >;

    "CriticalSafeguardActivated(uint256,string,uint256)": TypedContractEvent<
      CriticalSafeguardActivatedEvent.InputTuple,
      CriticalSafeguardActivatedEvent.OutputTuple,
      CriticalSafeguardActivatedEvent.OutputObject
    >;
    CriticalSafeguardActivated: TypedContractEvent<
      CriticalSafeguardActivatedEvent.InputTuple,
      CriticalSafeguardActivatedEvent.OutputTuple,
      CriticalSafeguardActivatedEvent.OutputObject
    >;

    "ElevatedSafeguardActivated(uint256,uint256,uint256)": TypedContractEvent<
      ElevatedSafeguardActivatedEvent.InputTuple,
      ElevatedSafeguardActivatedEvent.OutputTuple,
      ElevatedSafeguardActivatedEvent.OutputObject
    >;
    ElevatedSafeguardActivated: TypedContractEvent<
      ElevatedSafeguardActivatedEvent.InputTuple,
      ElevatedSafeguardActivatedEvent.OutputTuple,
      ElevatedSafeguardActivatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "RiskResponseExecuted(uint256,string,uint256,address,uint256)": TypedContractEvent<
      RiskResponseExecutedEvent.InputTuple,
      RiskResponseExecutedEvent.OutputTuple,
      RiskResponseExecutedEvent.OutputObject
    >;
    RiskResponseExecuted: TypedContractEvent<
      RiskResponseExecutedEvent.InputTuple,
      RiskResponseExecutedEvent.OutputTuple,
      RiskResponseExecutedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "ThresholdsUpdated(uint256,uint256,uint256,uint256)": TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;
    ThresholdsUpdated: TypedContractEvent<
      ThresholdsUpdatedEvent.InputTuple,
      ThresholdsUpdatedEvent.OutputTuple,
      ThresholdsUpdatedEvent.OutputObject
    >;

    "UnauthorizedAccessAttempt(address,uint256)": TypedContractEvent<
      UnauthorizedAccessAttemptEvent.InputTuple,
      UnauthorizedAccessAttemptEvent.OutputTuple,
      UnauthorizedAccessAttemptEvent.OutputObject
    >;
    UnauthorizedAccessAttempt: TypedContractEvent<
      UnauthorizedAccessAttemptEvent.InputTuple,
      UnauthorizedAccessAttemptEvent.OutputTuple,
      UnauthorizedAccessAttemptEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
