/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockWorldID,
  MockWorldIDInterface,
} from "../../../contracts/mocks/MockWorldID";

const _abi = [
  {
    inputs: [
      {
        internalType: "bool",
        name: "_shouldRevert",
        type: "bool",
      },
    ],
    name: "setShouldRevert",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "shouldRevert",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256[8]",
        name: "",
        type: "uint256[8]",
      },
    ],
    name: "verifyProof",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101a6806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80633bc778e3146100465780636813d7871461005b578063d3072d821461007c575b600080fd5b6100596100543660046100ec565b61009d565b005b610059610069366004610147565b6000805460ff1916911515919091179055565b6000546100899060ff1681565b604051901515815260200160405180910390f35b60005460ff16156100e45760405162461bcd60e51b815260206004820152600d60248201526c24b73b30b634b210383937b7b360991b604482015260640160405180910390fd5b505050505050565b6000806000806000806101a080888a03121561010757600080fd5b873596506020880135955060408801359450606088013593506080880135925088818901111561013657600080fd5b5060a0870190509295509295509295565b60006020828403121561015957600080fd5b8135801515811461016957600080fd5b939250505056fea2646970667358221220aa6fc6457d74f294c4c4df86be496ed1219bb6219277a9a3d941de7378f0943d64736f6c63430008180033";

type MockWorldIDConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockWorldIDConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockWorldID__factory extends ContractFactory {
  constructor(...args: MockWorldIDConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockWorldID & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockWorldID__factory {
    return super.connect(runner) as MockWorldID__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockWorldIDInterface {
    return new Interface(_abi) as MockWorldIDInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockWorldID {
    return new Contract(address, _abi, runner) as unknown as MockWorldID;
  }
}
